<?php
/**
 * Title: 業種セット — 建設・工務店
 * Slug: robse-one/industry-construction
 * Categories: robse-one, featured
 * Description: 建設会社や工務店向けのトップページ構成例。
 * Viewport Width: 1200
 */
?>
<!-- wp:cover {"dimRatio":0,"overlayColor":"mint","textColor":"ink","minHeight":440,"minHeightUnit":"px","align":"wide","className":"robse-hero","layout":{"type":"constrained"}} --><div class="wp-block-cover alignwide robse-hero has-ink-color has-text-color" style="min-height:440px"><span aria-hidden="true" class="wp-block-cover__background has-mint-background-color has-background-dim-0 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"textColor":"ocean","fontSize":"small"} --><p class="has-ocean-color has-text-color has-small-font-size">BUILD WITH CARE</p><!-- /wp:paragraph --><!-- wp:heading {"level":1,"fontSize":"display"} --><h1 class="wp-block-heading has-display-font-size">暮らしに寄り添う<br>ものづくり。</h1><!-- /wp:heading --><!-- wp:paragraph --><p>施工エリアと得意分野を簡潔に紹介してください。</p><!-- /wp:paragraph --></div></div><!-- /wp:cover -->
<!-- wp:group {"align":"wide","className":"robse-section","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide robse-section"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">家づくり・施工サービス</h2><!-- /wp:heading --><!-- wp:columns --><div class="wp-block-columns"><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"robse-card","layout":{"type":"constrained"}} --><div class="wp-block-group robse-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">新築・注文住宅</h3><!-- /wp:heading --><!-- wp:paragraph --><p>設計方針、素材、相談から完成までの流れ。</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"robse-card","layout":{"type":"constrained"}} --><div class="wp-block-group robse-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">リフォーム</h3><!-- /wp:heading --><!-- wp:paragraph --><p>対応する工事や、相談・現地調査の流れ。</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">施工事例</h2><!-- /wp:heading --><!-- wp:paragraph --><p>事例写真、工事内容、地域、施工時期を掲載してください。</p><!-- /wp:paragraph --><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">お問い合わせ</h2><!-- /wp:heading --><!-- wp:paragraph --><p>対応エリアと問い合わせ方法を記載してください。</p><!-- /wp:paragraph --></div><!-- /wp:group -->
