<?php
/**
 * Title: 業種セット — 採用
 * Slug: robse-one/industry-recruitment
 * Categories: robse-one, featured
 * Description: 採用・求人向けランディングページの構成例。
 * Viewport Width: 1200
 */
?>
<!-- wp:cover {"dimRatio":0,"overlayColor":"mint","textColor":"ink","minHeight":440,"minHeightUnit":"px","align":"wide","className":"robse-hero","layout":{"type":"constrained"}} --><div class="wp-block-cover alignwide robse-hero has-ink-color has-text-color" style="min-height:440px"><span aria-hidden="true" class="wp-block-cover__background has-mint-background-color has-background-dim-0 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"textColor":"ocean","fontSize":"small"} --><p class="has-ocean-color has-text-color has-small-font-size">CAREERS</p><!-- /wp:paragraph --><!-- wp:heading {"level":1,"fontSize":"display"} --><h1 class="wp-block-heading has-display-font-size">次の一歩を、<br>ここから。</h1><!-- /wp:heading --><!-- wp:paragraph --><p>仕事の魅力と、チームが大切にしていることを紹介してください。</p><!-- /wp:paragraph --></div></div><!-- /wp:cover -->
<!-- wp:group {"align":"wide","className":"robse-section","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide robse-section"><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">働く環境</h2><!-- /wp:heading --><!-- wp:columns --><div class="wp-block-columns"><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"robse-card","layout":{"type":"constrained"}} --><div class="wp-block-group robse-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">仕事内容</h3><!-- /wp:heading --><!-- wp:paragraph --><p>役割、1日の流れ、必要な経験を具体的に紹介してください。</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"robse-card","layout":{"type":"constrained"}} --><div class="wp-block-group robse-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">制度・サポート</h3><!-- /wp:heading --><!-- wp:paragraph --><p>勤務条件、福利厚生、育成支援を正確に記載してください。</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --><!-- wp:heading {"level":2} --><h2 class="wp-block-heading">募集要項</h2><!-- /wp:heading --><!-- wp:list --><ul><li>雇用形態・勤務地</li><li>勤務時間・休日</li><li>給与・応募条件</li><li>選考の流れ・応募先</li></ul><!-- /wp:list --><!-- wp:paragraph --><p>応募前に必ず最新の募集条件へ更新してください。</p><!-- /wp:paragraph --></div><!-- /wp:group -->
