<?php
/**
 * Title: 料金プラン
 * Slug: robse-one/pricing
 * Categories: robse-one
 * Viewport Width: 1200
 */
?>
<!-- wp:group {"align":"wide","className":"robse-section","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide robse-section"><!-- wp:heading {"textAlign":"center","level":2} --><h2 class="wp-block-heading has-text-align-center">料金プラン</h2><!-- /wp:heading --><!-- wp:columns --><div class="wp-block-columns"><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"robse-card","layout":{"type":"constrained"}} --><div class="wp-block-group robse-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">スタンダード</h3><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">¥ 00,000〜</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>基本サービス</li><li>サポート</li><li>納期の目安</li></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"url":"#contact"} --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#contact">相談する</a></div><!-- /wp:button --></div><!-- /wp:group --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"robse-card","layout":{"type":"constrained"}} --><div class="wp-block-group robse-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">カスタム</h3><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">お見積もり</p><!-- /wp:paragraph --><!-- wp:list --><ul><li>ご要望に合わせて設計</li><li>個別サポート</li><li>まずはご相談ください</li></ul><!-- /wp:list --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button {"url":"#contact"} --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#contact">見積もりを依頼</a></div><!-- /wp:button --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --><!-- wp:paragraph {"align":"center","fontSize":"small"} --><p class="has-text-align-center has-small-font-size">※ 表示価格や提供内容は、公開前に実際の条件に合わせてご確認ください。</p><!-- /wp:paragraph --></div><!-- /wp:group -->
