<?php
/**
 * Title: サービス紹介
 * Slug: robse-one/services
 * Categories: robse-one
 * Viewport Width: 1200
 */
?>
<!-- wp:group {"align":"wide","anchor":"services","className":"robse-section","layout":{"type":"constrained"}} --><div class="wp-block-group alignwide robse-section" id="services"><!-- wp:paragraph {"align":"center","textColor":"ocean","fontSize":"small"} --><p class="has-text-align-center has-ocean-color has-text-color has-small-font-size">OUR SERVICES</p><!-- /wp:paragraph --><!-- wp:heading {"textAlign":"center","level":2} --><h2 class="wp-block-heading has-text-align-center">サービスのご案内</h2><!-- /wp:heading --><!-- wp:columns --><div class="wp-block-columns"><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"robse-card","layout":{"type":"constrained"}} --><div class="wp-block-group robse-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">サービス A</h3><!-- /wp:heading --><!-- wp:paragraph --><p>サービスの概要と、お客様にとってのメリットを紹介します。</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>サービスの詳細ページへのリンクを設定してください。</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"robse-card","layout":{"type":"constrained"}} --><div class="wp-block-group robse-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">サービス B</h3><!-- /wp:heading --><!-- wp:paragraph --><p>対象となるお客様や、提供する内容を簡潔に説明します。</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>サービスの詳細ページへのリンクを設定してください。</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:group {"className":"robse-card","layout":{"type":"constrained"}} --><div class="wp-block-group robse-card"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">サービス C</h3><!-- /wp:heading --><!-- wp:paragraph --><p>ほかのサービスとの違いや、選ぶ理由を紹介します。</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>サービスの詳細ページへのリンクを設定してください。</p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->
